---
- name: ensure hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
  become: true

- name: ensure /etc/hostname
  copy:
    content: "{{ inventory_hostname_short }}"
    dest: "{{ hostname_hostname_file }}"
    group: root
    owner: root
    mode: 0644
  become: true
